query sermonsQuery {
  resources(first: 10) {
    nodes {
      id
      name
      snippet
      content
      audioUrl
      youtubeUrl
      bannerUrl
      authors {
        id
        name
      }
      topics {
        id
        name
      }
      scriptures {
        id
        name
      }
    }
	}
}
