query sermonQuery($ids: [ID!]) {
  resources(ids: $ids) {
    nodes {
      id
      name
      snippet
      content
      audioUrl
      youtubeUrl
      bannerUrl
      authors {
        id
        name
      }
      topics {
        id
        name
      }
      scriptures {
        id
        name
      }
    }
	}
}
