query sermonQuery($ids: [ID!]) {
  resources(ids: $ids) {
    nodes {
      id
      name
      snippet
      content
      audioUrl
      youtubeUrl
      bannerUrl
      sermonNotes
      connectGroupNotes
      authors {
        id
        name
      }
      topics {
        id
        name
      }
      connectionScriptures {
        id
        range
        content
        scripture {
          id
          name
        }
      }
    }
	}
}
