query stepQuery($ids: [ID!]) {
  steps(ids: $ids) {
    nodes {
      id
      name
      content
      bannerUrl
      locationConnectionSteps {
        nodes {
          id
          elvantoFormId
          mailChimpUserId
          mailChimpAudienceId
          content
          location {
            id
            name
          }
        }
      }
    }
	}
}
