query latestSermonQuery {
  resources(resourceType: "sermon", first: 1) {
    edges {
      node {
        id
        publishedAt
        name
        authors {
          name
        }
        connectionScriptures {
          range
          scripture {
            name
          }
        }
        series {
          id
					bannerUrl
        }
      }
    }
  }
}
